# Generated by Django 5.2.12 on 2026-04-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_wishlist_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='customer_or_user_id_ea0fcf_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='customer_or_order_n_1eea27_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='customer_or_order_s_5ea6ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='customer_or_is_paid_156c39_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='customer_or_order_i_47b9d9_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='customer_or_seller__fcdd50_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='customer_or_variant_50e3f9_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='final_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ordered_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price_at_purchase',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
    ]
