# Generated by Django 5.2.11 on 2026-02-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_sellerprofile_seller_sell_is_veri_38db58_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
