# Generated by Django 5.2.11 on 2026-02-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_product_approval_status_product_is_cancellable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='seller_banners/'),
        ),
    ]
