# Generated by Django 5.2.11 on 2026-03-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_is_staff'),
        ('seller', '0008_remove_product_image_alter_product_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='core.subcategory'),
        ),
    ]
