# Generated by Django 5.2.11 on 2026-03-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_alter_attribute_id_alter_attributeoption_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
