# Generated by Django 5.2.11 on 2026-03-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_remove_productimage_image_url_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.IntegerField(default=5),
        ),
    ]
