# Generated by Django 5.2.12 on 2026-04-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0019_merge_20260324_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
