# Generated by Django 5.2.11 on 2026-03-23 11:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnadmin', '0003_product_rejection_reason'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productrejectionreason',
            new_name='bnadmin_pro_product_765f49_idx',
            old_name='bnadmin_pr_product_9f6b7f_idx',
        ),
        migrations.AlterField(
            model_name='productrejectionreason',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
