# Generated by Django 5.2.12 on 2026-04-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnadmin', '0004_rename_bnadmin_pr_product_9f6b7f_idx_bnadmin_pro_product_765f49_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
